spring.application.name=notes
#spring.security.user.name=user
#spring.security.user.password=pass
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.server=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG